### ISSUE TITLE
Question: Will I be able to use this for other shadcn components?

### ISSUE THREAD

**Issue by invalidred** [mit-27/fresh-shadcn-buttons#2]
Thank you for taking the time to document your work. I'd like to know if I could use your work as a good starting point and add other "non button" components to fresh? Would it work?

**Comment by mit-27** [comment]
Hello @invalidred, thank you for your interest! I tweaked the component for this issue, but it’s not a viable long-term solution. I learned from Discord that there’s a repository where all components have been converted using aliasing. I’ve opened an issue there, and you might want to contribute as well.

Thank you

https://github.com/nikogoli/testing-shadcn-ui-in-fresh

**Comment by invalidred** [comment]
Gotcha, TYSM @mit-27
